### ISSUE TITLE
Invoking c++ function from JS-code are not working correctly

### ISSUE THREAD

**Issue by niXman** [annulen/webkit#605]
Hello again.

I have code like this:
```cpp
struct MyClass: QObject {
   QWebView *wv;

   MyClass() {
      setObjectName("Communication");
      connect(wv->page()->mainFrame(), SIGNAL(javaScriptWindowObjectCleared())
        ,this, SLOT(addJSObject())
      );
   }
   void addJSObject() {
      wv->page()->mainFrame()->addToJavaScriptWindowObject(objectName(), this);
   }
   void invoke(int, int, QString api, QString data) {}
};
```
When I try to invoke `Communication.invoke(1, 2, "3", "4");`  in the Inspect console I see the `Communication.invoke is not a function. (In 'Communication.invoke(1, 2, "3", "4")', 'Communication.invoke' is undefined)` error.

But this code works fine using qt-4.8. Ideas?

P.S.
Yes, I still use the QtWebKit from MSYS2...

**Comment by annulen** [comment]
>But this code works fine using qt-4.8

That's impossible. To be usable in JS, your `invoke` method must be visible to Qt's meta-object system, i.e. be signal, slot, or Q_INVOKABLE

**Comment by niXman** [comment]
Of course, `invoke()` is slot:
```cpp
struct MyClass: QObject {
public slots:
   void invoke(int, int, QString api, QString data) {}
};
```
As I understand you, you have no idea and this code should work?

**Comment by annulen** [comment]
I don't see `public slots` in your original snippet. Otherwise, yes, no idea

**Comment by niXman** [comment]
But yas, I stiil can invoke JS functions from C++ using `evaluateJavaScript()`..

**Comment by annulen** [comment]
Make sure that you also have Q_OBJECT macro, and your class is actually processed by moc. QMetaObject should return your method

**Comment by niXman** [comment]
[untitled.zip](https://github.com/annulen/webkit/files/1228331/untitled.zip)

> Make sure that you also have Q_OBJECT macro

yes.

> and your class is actually processed by moc

yes.

> QMetaObject should return your method\

yes.

In attachments I put the minimal example. If you run it, in the Inspect console you can type the `Communication.` and after that you will see the all `QMainWindow` methods, but none of my methods...

**Comment by niXman** [comment]
My bad. Sorry for the noise.

Closed.
