### ISSUE TITLE
can't build with qt 5.12 on windows libjpeg update

### ISSUE THREAD

**Issue by xlazom00** [annulen/webkit#789]
I can't build with latest qt 5.12
it looks like another update of libjpeg

qt5\qtbase\src\3rdparty\libjpeg\src\jmorecfg.h(242): error C2371: 'boolean': redefinition; different basic types

**Comment by xlazom00** [comment]
btw my patch don't work with qt 5.11 so some ifdef will be nice or some other solution

**Comment by xlazom00** [comment]
@annulen  all fine with qt 5.12 and ubuntu 16.04,  windows MSVC 2015, macos 10.14(xcode 10)
but we will need if def for qt 5.11 what do you think ?

**Comment by FVerbum** [comment]
I can't to complile with your patches.
Please look
https://github.com/annulen/webkit/issues/801

**Comment by FVerbum** [comment]
Thanks for answer.
I don't Conan.
Look this: https://github.com/annulen/webkit/issues/804

**Comment by herbmillerjr** [comment]
I made an update to the Windows libs in case you want to go that route.

[http://www.sky-meyg.com/downloads/qtwebkit-libs-win.zip]

This updates libjpeg, libpng, and zlib, and does not require the jpeg .dll. Both 64-bit and 32-bit libraries are there and I tested building for each. I built them with VS 2017, so let me know if anyone runs into problems on VS 2015 with them. I can always rebuild with that.

**Comment by annulen** [comment]
@herbmillerjr Nice job! Do you have a script to automate this procedure?

**Comment by herbmillerjr** [comment]
Not yet, but it would be wise for me to write one. If the next bump of our software to Qt LTS takes this long my head will get rolled. ;-)

Does Qt publish in the source any place we could check to see what versions of what libraries we need to build? For instance, I could point a script to Qt 5.12 source directory and it could determine it needs libjpeg-turbo-2.0.0.

**Comment by annulen** [comment]
>Does Qt publish in the source any place we could check to see what versions of what libraries we need to build? For instance, I could point a script to Qt 5.12 source directory and it could determine it needs libjpeg-turbo-2.0.0

There is a hack in QtWebKit already which can rebuild jpeg library from sources in QtBase (and similarly for png). Actually that's one of two ways to build QtWebKit against prebuilt QtBase without any possible run-time conflicts (other is to use QtBase built without use of bundled libraries, and use the same libraries for QtWebKit)

**Comment by dougmassay** [comment]
> I built them with VS 2017, so let me know if anyone runs into problems on VS 2015 with them. I can always rebuild with that.

Unless you used the 2015 toolchain with VS2017, an end-to-end VS2015 solution (Qt5/WebKit/Application) won't be possible with these libs, will it? VS2017 projects can utilize VS2015-built libs, but is the reverse true (with only the VS2015 redist installed)?

**Comment by annulen** [comment]
I don't think it's a good idea to use VS2015 in 2019

**Comment by dougmassay** [comment]
It's not as if VS2017 doesn't have it's own faults. Besides ... Qt still distributes a VS2015-built binary (and still supports being built with VS2015) and the minimum requirement for this version of QtWebKit is in fact VS2015.

Good idea or not, there's still a ton of development being done with VS2015. I myself don't plan to abandon it until I'm forced to do so. I'm quite prepared for that eventuality, but I'll likely go directly to VS2019 when that time comes (bypassing VS2017 altogether). I've seen no compelling reasons to rush that plan.

Never been a fan of dropping support for older systems/toolchains just because newer/shinier ones are available. That's how Qt ended up on my shit-list in the first place. And why I ended up here looking for QtWebKit alternatives. ;)

**Comment by herbmillerjr** [comment]
Goodness @dougmassay, you could have just said, "Could you make a VS2015 build for those of us using it, please?" I'll put one together this afternoon should time permit.

**Comment by dougmassay** [comment]
> Goodness @dougmassay, you could have just said, "Could you make a VS2015 build for those of us using it, please?" I'll put one together this afternoon should time permit.

Except that I don't _need_ anyone to make a build for me. So don't put yourself out on my account. But perhaps others might appreciate it. I was merely letting you know (since you seemed genuinely concerned that someone might "run into problems on VS 2015 with them") that there certainly _would_ be problems with such a scenario.

And I DID add a wink after all. ;)

**Comment by annulen** [comment]
@herbmillerjr I need your thoughts on JPEGImageDecoder patch, i.e. what is the right way to do 0003-compile-with-qt5.12-libjpeg.patch (0002-support-qt-5.12-libjpeg.patch is applied already)

https://testresults.qt.io/logs/qt/qtwebkit/aaebeee5cd532f298051d58ef43d8c8aef3b0b89/WindowsWindows_10x86_64WindowsWindows_10x86MSVC2017qtci-windows-10-x86_64-10-e6fc8cDebugAndRelease_ForceDebugInfo_OpenGLDynamic_Release/0929c92ae51bcf2b402060d81e5e3cd81810ed1d/build_1559780099/log.txt.gz

**Comment by annulen** [comment]
OK, origin of 0003 patch is https://codereview.qt-project.org/c/qt/qtbase/+/246256

**Comment by annulen** [comment]
Before Qt 5.12 there was following in jconfig.h:
```diff
-/* Define "boolean" as unsigned char, not int, on Windows systems. */
#ifdef _WIN32
#ifndef __RPCNDR_H__           /* don't conflict if rpcndr.h already read */
typedef unsigned char boolean;
#endif
#define HAVE_BOOLEAN           /* prevent jmorecfg.h from redefining it */
#endif
```

**Comment by annulen** [comment]
We should probably drop direct use of libjpeg if system library is not found, and use QImageReader instead. In the beginning using WebKit decoders for all image formats seemed like a good idea (see https://github.com/annulen/webkit/wiki/FAQ#why-so-many-dependencies-besides-qt), however for jpeg cons outweigh pros:

**Pros**
* Same behavior of decoder with WebKitGTK and other non-Apple ports
* Incremental decoding
* Use of TURBO_JPEG_RGB_SWIZZLE code path with jpeg-turbo (optimization, not implemented in Qt)
* Possible to use IMAGE_DECODER_DOWN_SAMPLING code path for memory saving
* Possible to use QCMSLIB code path, see #297
**Cons**
* Fragile build setup when using libjpeg bundled with Qt, which is broken second time after Qt update already and this may happen in future again
* Building QtWebKit from sources against prebuilt Qt on Windows and macOS requires either full Qt sources (and some dancing around), or using exactly the same libjpeg vendor and version as `qjpeg` image plugin to avoid rendering bugs (which we aimed to avoid in the first item) caused by clash of 2 libjpeg's in same process

**Comment by annulen** [comment]
For png situation is a bit different: it never caused issues for users, there were no breakages on Qt updates, using libpng directly allows us to support APNG format missing in Qt, progressive decoding may be more important than for jpeg because of larger file size

**Comment by annulen** [comment]
Goog riddance
https://codereview.qt-project.org/c/qt/qtwebkit/+/264316
