### ISSUE TITLE
Installation on Ubuntu Xenial with default qt5

### ISSUE THREAD

**Issue by kmike** [annulen/webkit#556]
Hi, 

I'm using Qt 5.5.1 provided by Ubuntu, and can't make qtwebkit install using instructions from wiki; it fails with the following error:

```
cmake -DPORT=Qt -DCMAKE_BUILD_TYPE=Release ../..
-- Could NOT find Ruby (missing:  RUBY_INCLUDE_DIR RUBY_LIBRARY RUBY_CONFIG_INCLUDE_DIR) (found suitable version "2.3.0", minimum required is "1.9")
-- Found ICU header files in /usr/include/x86_64-linux-gnu
-- Found ICU libraries: /usr/lib/x86_64-linux-gnu/libicuuc.so
-- Found WEBP: /usr/include
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5WebChannel"
  with any of the following names:

    Qt5WebChannelConfig.cmake
    qt5webchannel-config.cmake

  Add the installation prefix of "Qt5WebChannel" to CMAKE_PREFIX_PATH or set
  "Qt5WebChannel_DIR" to a directory containing one of the above files.  If
  "Qt5WebChannel" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  Source/cmake/OptionsQt.cmake:450 (find_package)
  Source/cmake/WebKitCommon.cmake:47 (include)
  CMakeLists.txt:135 (include)
```

It seems QtWebChannel is required, and it is not provided in 16.04 packages (https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1579265).

**Comment by annulen** [comment]
That's really surprising to me, as QtWebChannel is quite a simple library with few dependencies.

You have following ways to work around this problem:
* I guess Scrapy doesn't use QML API, so you can safely build with -DENABLE_WEBKIT2=OFF, it will disable WebChannel dependency as well
* You can disable just WebChannel by using -DENABLE_QT_WEBCHANNEL=OFF. I can make it optional feature, i.e. disable automatically if WebChannel is not available, however QML API is much less useful without it.

**Comment by annulen** [comment]
BTW, do you have public PPA?

**Comment by kmike** [comment]
Thanks for the pointer! I don't need qml, so -DENABLE_WEBKIT2=OFF sounds like a good option. Splash doesn't have a PPA, it uses Docker for distribution; I'm trying to figure out how to create a required Docker image and at the same time make Docker building fast, so that build sccripts can be used to run tests on Travis.

With ENABLE_WEBKIT=OFF cmake still fails:

```
cmake -DPORT=Qt -DENABLE_WEBKIT2=OFF -DCMAKE_BUILD_TYPE=Release ../..
-- Could NOT find Ruby (missing:  RUBY_INCLUDE_DIR RUBY_LIBRARY RUBY_CONFIG_INCLUDE_DIR) (found suitable version "2.3.0", minimum required is "1.9")
-- Disabling ENABLE_QT_WEBCHANNEL since ENABLE_WEBKIT2 is disabled.
-- Found ICU header files in /usr/include/x86_64-linux-gnu
-- Found ICU libraries: /usr/lib/x86_64-linux-gnu/libicuuc.so
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find GLIB (missing: GLIB_INCLUDE_DIRS GLIB_LIBRARIES
  GLIB_GIO_LIBRARIES GLIB_GOBJECT_LIBRARIES) (Required is at least version
  "2.36")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  Source/cmake/FindGLIB.cmake:109 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  Source/cmake/OptionsQt.cmake:590 (find_package)
  Source/cmake/WebKitCommon.cmake:47 (include)
  CMakeLists.txt:135 (include)
```

This can be fixed by running `sudo apt install glib2.0` - it'd be nice to add glib2.0 to a list of packages at https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Linux. I also had some problems with gstreamer, so I disabled it for now as well, using `-DUSE_GSTREAMER=OFF`.

The last issue is qt location - to override system-installed qt prefix should be set to /usr, while default is /usr/local. 

I also needed qtbase5-private-dev package (as you suggested in https://github.com/annulen/webkit/issues/309#issuecomment-246100946.

Command which worked:

```
cmake -DPORT=Qt -DCMAKE_BUILD_TYPE=Release \ 
    -DENABLE_WEBKIT2=OFF \
    -DUSE_GSTREAMER=OFF \ 
    -DCMAKE_INSTALL_PREFIX=/usr ../..
```

I'm not sure why, but packages from http://repo.paretje.be/xenial-backports didn't work for me; after installing these deb files using `dpkg -i` PyQT was no longer able to find webkit at configure time. It could be an error on my side. 

I'd love not having to maintain binary qt, qtwebkit, etc. packages myself, so next step is to try Ubuntu Xenial, binary files you're providing for tp5 (https://github.com/annulen/webkit/releases) and qt 5.8 from https://launchpad.net/~beineri/+archive/ubuntu/opt-qt58-xenial. On OS X + qt 5.8 installed via homebrew this method didn't work (https://github.com/annulen/webkit/issues/508?).

I'm far from being an expert in all this stuff, so if you have any suggestions or pointers they are very much appreciated!

**Comment by annulen** [comment]
-DUSE_GSTREAMER=OFF is the right thing to do if you don't need HTML5 audio/video and related technologies. This option eliminates dependency on GLib as well.

As for CMAKE_INSTALL_PREFIX - by default it should be set to the installation prefix of used Qt libraries, as reported by `qmake -query QT_INSTALL_PREFIX` (where qmake is from used Qt). Maybe you just needed clean build.

**Comment by kmike** [comment]
Installing qt5.8 and then copying binary tp5 files over it didn't work for me on Ubuntu Xenial. PyQT was able to find webkit and build successfully, but at runtime it fails with the following error:

```
Traceback (most recent call last):
  File "/app/bin/splash", line 3, in <module>
    from splash.server import main
  File "/app/splash/server.py", line 12, in <module>
    from splash.qtutils import init_qt_app
  File "/app/splash/qtutils.py", line 17, in <module>
    from PyQt5.QtWebKit import QWebSettings
ImportError: libicuuc.so.56: cannot open shared object file: No such file or directory
```

It looks like binary files are built for libicu 56, but Xenial provides 55, and later Ubuntu versions provide 57: https://packages.ubuntu.com/search?keywords=libicu-dev.

**Comment by annulen** [comment]
TP5 binaries are supposed to work with official Qt 5.8 binaries, that come with ICU 56.1. They are built in Qt CI system and use same environment.

**Comment by kmike** [comment]
Thanks! After a bit of wrestling with official qt 5.8 installer I was able to get it working with your webkit fork. I needed to install a few extra X-related packages to the Docker image, gstreamer, and use a custom Qt install script in order to make installer non-interactive. 

On a few websites I tried it seems to work fine, but http://html5test.com/ doesn't work; it only shows "About HTML5test" section and no scores. I'm debugging this now.

**Comment by annulen** [comment]
Apparently it's a bug in html5test.com page, it starts working after enabling MediaSource (`setAttribute(QWebSettings::MediaSourceEnabled, true)`)

**Comment by annulen** [comment]
It's also known that test works fine on Windows where MediaSource is not currently available. It may be a good idea to debug this, or report to site authors

**Comment by kmike** [comment]
Hm, I can't set it in PyQT because `type object 'QWebSettings' has no attribute 'MediaSourceEnabled'`; I can't find MediaSourceEnabled in qt docs as well - is it something implemented in this updated webkit? Is there a value I can use without using this constant?

**Comment by annulen** [comment]
Yes, you can use value of `Accelerated2dCanvasEnabled` + 1

**Comment by kmike** [comment]
Woohoo, it worked - thanks @annulen! 
There are some problems with fonts as well (html5test doesn't show a large number with a score, seemingly because of a missing font), I'll try to install more font packages.

**Comment by annulen** [comment]
Large fonts are not rendered because of https://bugreports.qt.io/browse/QTBUG-59799 (see #452)

**Comment by kmike** [comment]
Aha, you have an answer for every problem :) So the solution is to wait for qt5.9 compatibility in this repo and for the next binary release? Are you planning to make next binary release against qt 5.9?

**Comment by annulen** [comment]
Yes, pretty soon

**Comment by kmike** [comment]
Update: all ~1.2K Splash tests pass with your fork, except for one issue: `window.innerWidth` is consistently 1px larger than `window.outerWidth`. For example, when innerWidth is 1024x768, outerWidth is 1023x767. They were the same in previous WebKit. I tried it in a few real browsers (Safari, Firefox, Chrome), and values are the same as well. Certainly not a big deal; I was not sure where to raise issue and if it is an issue at all, so just FYI.

**Comment by annulen** [comment]
I think this is the result of https://codereview.qt-project.org/#/c/183477/

outerWidth includes size of window's frame now

**Comment by kmike** [comment]
Thanks @annulen, that's amazing you know all these things :)
